"""add similar_to table

Revision ID: 0cd746fe1239
Revises: 4b7959209672
Create Date: 2026-03-12 20:07:00.442456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd746fe1239'
down_revision = '4b7959209672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('similar_to',
    sa.Column('polish_1_id', sa.Integer(), nullable=False),
    sa.Column('polish_2_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('polish_1_id < polish_2_id', name='ck_similar_canonical_order'),
    sa.CheckConstraint('polish_1_id <> polish_2_id', name='ck_similar_not_self'),
    sa.ForeignKeyConstraint(['polish_1_id'], ['polishes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['polish_2_id'], ['polishes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('polish_1_id', 'polish_2_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('similar_to')
    # ### end Alembic commands ###
