"""Add mani_logs-tags relationship

Revision ID: 39d079ac8317
Revises: 73cfc6e00f74
Create Date: 2025-04-06 15:43:12.314430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d079ac8317'
down_revision = '73cfc6e00f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mani_logs_tags',
    sa.Column('mani_log_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mani_log_id'], ['mani_logs.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('mani_log_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mani_logs_tags')
    # ### end Alembic commands ###
