"""Convert color_family from text to Enum

Revision ID: 48aa84b553a0
Revises: a40d97d6357a
Create Date: 2025-04-07 16:23:47.163915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48aa84b553a0'
down_revision = 'a40d97d6357a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polishes', schema=None) as batch_op:
        batch_op.alter_column('polish_type',
               existing_type=mysql.ENUM('color', 'top coat', 'base coat', 'stamping polish', 'other'),
               nullable=False)
        batch_op.alter_column('color_family',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('clear/white', 'black', 'grey/silver', 'nude/gold/brown', 'red', 'coral/orange', 'yellow', 'green', 'teal/turq/aqua', 'blue', 'indigo', 'violet', 'fuchsia', 'pink', 'base/top coat', name='color_family_types'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polishes', schema=None) as batch_op:
        batch_op.alter_column('color_family',
               existing_type=sa.Enum('clear/white', 'black', 'grey/silver', 'nude/gold/brown', 'red', 'coral/orange', 'yellow', 'green', 'teal/turq/aqua', 'blue', 'indigo', 'violet', 'fuchsia', 'pink', 'base/top coat', name='color_family_types'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('polish_type',
               existing_type=mysql.ENUM('color', 'top coat', 'base coat', 'stamping polish', 'other'),
               nullable=True)

    # ### end Alembic commands ###
