"""Add brands.abbrev field

Revision ID: 4b7959209672
Revises: 4f1223c6a380
Create Date: 2025-08-23 20:03:56.728993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7959209672'
down_revision = '4f1223c6a380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abbrev', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_column('abbrev')

    # ### end Alembic commands ###
