"""Turn polishes_mani_logs into model class association object, add n_fingers and n_coats

Revision ID: 4f1223c6a380
Revises: 68c00f8ef502
Create Date: 2025-07-16 19:35:35.860304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1223c6a380'
down_revision = '68c00f8ef502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polishes_mani_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n_fingers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('n_coats', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polishes_mani_logs', schema=None) as batch_op:
        batch_op.drop_column('n_coats')
        batch_op.drop_column('n_fingers')

    # ### end Alembic commands ###
