"""Recreated schema

Revision ID: 59a42f18c63a
Revises: 
Create Date: 2025-02-10 19:25:59.815572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a42f18c63a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.Column('type', sa.Enum('indie', 'boutique', 'mainstream', 'luxury', 'unknown', name='brand_types'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient_lib',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('vendor', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manicure_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mani_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_total', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand', sa.String(length=75), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('full_desc', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_log')
    op.drop_table('polish')
    op.drop_table('order_log')
    op.drop_table('manicure_log')
    op.drop_table('ingredient_lib')
    op.drop_table('brands')
    # ### end Alembic commands ###
