"""Make polish_type nullable

Revision ID: 68c00f8ef502
Revises: 48aa84b553a0
Create Date: 2025-04-07 16:30:49.798744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68c00f8ef502'
down_revision = '48aa84b553a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polishes', schema=None) as batch_op:
        batch_op.alter_column('color_family',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('clear/white', 'black', 'grey/silver', 'nude/gold/brown', 'red', 'coral/orange', 'yellow', 'green', 'teal/turq/aqua', 'blue', 'indigo', 'violet', 'fuchsia', 'pink', 'base/top coat', name='color_family_types'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polishes', schema=None) as batch_op:
        batch_op.alter_column('color_family',
               existing_type=sa.Enum('clear/white', 'black', 'grey/silver', 'nude/gold/brown', 'red', 'coral/orange', 'yellow', 'green', 'teal/turq/aqua', 'blue', 'indigo', 'violet', 'fuchsia', 'pink', 'base/top coat', name='color_family_types'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
