"""Update schema

Revision ID: a05b3726e0a1
Revises: 59a42f18c63a
Create Date: 2025-03-01 21:36:48.783743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a05b3726e0a1'
down_revision = '59a42f18c63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('vendor', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mani_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mani_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('order_total', sa.Float(), nullable=True),
    sa.Column('subtotal_polish', sa.Float(), nullable=True),
    sa.Column('subtotal_ingredient', sa.Float(), nullable=True),
    sa.Column('subtotal_other', sa.Float(), nullable=True),
    sa.Column('subtotal_ship_tax', sa.Float(), nullable=True),
    sa.Column('subtotal_discount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients_order_logs',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('order_log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['order_log_id'], ['order_logs.id'], ),
    sa.PrimaryKeyConstraint('ingredient_id', 'order_log_id')
    )
    op.create_table('ingredients_recipes',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('ingredient_id', 'recipe_id')
    )
    op.create_table('mani_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('mani_log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mani_log_id'], ['mani_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('polishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('polish_type', sa.Enum('color', 'top coat', 'base coat', 'stamping polish', 'other', name='polish_types'), nullable=True),
    sa.Column('color_family', sa.String(length=50), nullable=True),
    sa.Column('full_desc', sa.String(length=400), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id')
    )
    op.create_table('polishes_mani_logs',
    sa.Column('polish_id', sa.Integer(), nullable=False),
    sa.Column('mani_log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mani_log_id'], ['mani_logs.id'], ),
    sa.ForeignKeyConstraint(['polish_id'], ['polishes.id'], ),
    sa.PrimaryKeyConstraint('polish_id', 'mani_log_id')
    )
    op.create_table('polishes_mani_photos',
    sa.Column('polish_id', sa.Integer(), nullable=False),
    sa.Column('mani_photo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mani_photo_id'], ['mani_photos.id'], ),
    sa.ForeignKeyConstraint(['polish_id'], ['polishes.id'], ),
    sa.PrimaryKeyConstraint('polish_id', 'mani_photo_id')
    )
    op.create_table('polishes_order_logs',
    sa.Column('polish_id', sa.Integer(), nullable=False),
    sa.Column('order_log_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_log_id'], ['order_logs.id'], ),
    sa.ForeignKeyConstraint(['polish_id'], ['polishes.id'], ),
    sa.PrimaryKeyConstraint('polish_id', 'order_log_id')
    )
    op.create_table('swatch_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('polish_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['polish_id'], ['polishes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ingredient_lib')
    op.drop_table('recipe_log')
    op.drop_table('order_log')
    op.drop_table('polish')
    op.drop_table('manicure_log')
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=75),
               nullable=False)
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=75),
               nullable=True)
        batch_op.drop_column('website_url')

    op.create_table('manicure_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mani_date', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('polish',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('brand', mysql.VARCHAR(length=75), nullable=True),
    sa.Column('color', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('full_desc', mysql.VARCHAR(length=400), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_date', mysql.DATETIME(), nullable=True),
    sa.Column('order_total', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('recipe_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('ingredient_lib',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('vendor', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('swatch_photos')
    op.drop_table('polishes_order_logs')
    op.drop_table('polishes_mani_photos')
    op.drop_table('polishes_mani_logs')
    op.drop_table('polishes')
    op.drop_table('mani_photos')
    op.drop_table('ingredients_recipes')
    op.drop_table('ingredients_order_logs')
    op.drop_table('recipes')
    op.drop_table('order_logs')
    op.drop_table('mani_logs')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
