"""Add destashed_flag to Polish

Revision ID: a40d97d6357a
Revises: 39d079ac8317
Create Date: 2025-04-06 20:04:34.491631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40d97d6357a'
down_revision = '39d079ac8317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polishes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destashed_flag', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polishes', schema=None) as batch_op:
        batch_op.drop_column('destashed_flag')

    # ### end Alembic commands ###
